### ISSUE TITLE
Logo is not coming in Loading Advice

### ISSUE THREAD

**Issue by rungsiyan** [tggwlcube/CuBe_SCSC#2]
![11](https://cloud.githubusercontent.com/assets/9924463/5162613/1248b93e-73f4-11e4-923d-09ee685392e8.jpg)

**Comment by hemantbansal** [comment]
This issue is solved, Please create loading list with new release in SCSC Prod database and check the issue once again

**Comment by narongchaip** [comment]
Thank you.
